### PR TITLE
917 Fix tax percentage calculation on invoice

### LINKED ISSUE #917: Fix tax percentage on invoice
Either a couple of late night deadline mistakes here - or long day mistakes about to happen from me 😁 

> What would be the difference between effective and avg accross lines?

Line1: tax 10%, subtotal: $100, total: $110
line2: tax 0%, subtotal: $50, total $50
line3: tax 5%, subtotal: $100, total $105

subtotal: 250
total: 265

average: 5%  (sum of tax percentages / number of lines - 15 / 3) - 250*1.05 = 262.5 ❌ 
effective: 6%  (total amount of tax paid / total amount on invoice  - (265-250) / 265) -  250*1.06 = 265 ✅ 

> So the tax should also be broken down by type ?

Happy to just calculate it in the UI - but the tax percentage right now is actually probably harmful if anything

_Originally posted by @joshxg in https://github.com/openmsupply/remote-server/pull/908#discussion_r824424064_

### PR DESCRIPTION
**Pull request by andreievg**
closes #917 

as per issue and related comment

### CODE REVIEW

File: repository/src/tests.rs [hunk 1]
```diff
@@ -698,16 +698,16 @@ mod repository_test {
...
+            inline_edit(&stats_invoice_1, |mut u| {
+                u.invoice_id = invoice_1_id;
+                u.total_before_tax = 13.0;
+                u.total_after_tax = 18.0;
+                u.stock_total_before_tax = 3.0;
+                u.stock_total_after_tax = 3.0;
+                u.service_total_before_tax = 10.0;
+                u.service_total_after_tax = 15.0;
+                u
+            })
```
Comment (clemens-msupply) [inline repository/src/tests.rs:710]: Just out of interest, why did you use inline_edit here? just to protect against future changes to PricingRow?

**Review by clemens-msupply — APPROVED** [review]

File: repository/src/tests.rs (hunk 1 above)
Comment (andreievg) [reply repository/src/tests.rs:710]: It's because of tax_percentage, didn't want to re-calculate it for this test (since I've already added a test for it in invoice_query).
